
model_size: n
total_images: 3500
data: data
project: runs/classify/TX_covers_multiclass
epochs: 200
patience: 100
batch: 16
imgsz: 128
workers: 12
pretrained_model_path: yolo11${train.model_size}-cls.pt
name: batch${train.batch}_imgsz${train.imgsz}_${train.total_images}_n