hydra:
  run:
    dir: hydra_logs/${now:%Y-%m-%d_%H_%M_%S}
  # used for multi-runs -> maybe useful
  # sweep:
  #   dir: main_dir
  #   subdir: ${hydra.job.name}
defaults:
  - _self_
  - train: default
  - paths: default
tasks:
  # - label_images
  - class_specific_labeler
  # - predict
  # - curate_labels
  # - move_files
  # - train
  # - concat_labels

label_images:
  batch_prefix: TX
  storage: longterm_images # GROW_DATA or longterm_images
  image_folder: /mnt/research-projects/s/screberg/${label_images.storage}/semifield-cutouts
  start_date: 2022-10-12
  end_date: 2023-04-20
  sample_folder_count: 10
  parent_output_folder: cover_labels
  season: cover

predict:
  start_date: 2023-09-18
  end_date: 2024-05-16
  batch_prefix: MD
  image_folder: /mnt/research-projects/s/screberg/longterm_images/semifield-cutouts
  output_folder: predictions_test
  sample_folder_count: 10
  
  model_path: runs/classify/MD_covers/batch8_imgsz128_1030_n/weights/best.pt
  labels:
    0: broadleaf
    1: grass
    2: hairy_vetch
    3: non_target
  parallel_inference: True
  inference_batch_size: 256

move_files:
  labels_folder: results
  batch_prefix: TX
  longterm_storage_locations:
   - /mnt/research-projects/s/screberg/longterm_images/semifield-cutouts
   - /mnt/research-projects/s/screberg/GROW_DATA/semifield-cutouts
   - /home/psa_images/SemiF-AnnotationPipeline/data/semifield-cutouts
  output_folder: data
  test_size: 0.15
  max_workers: 16
  # only for common names that need to be grouped, one-to-one mapping taken care of in code
  common_name_grouping:
    grass:
      - cereal rye
      - alfalfa
      - maize
    # hairy vetch:
    #   - hairy vetch
    # broadleaf:
    #   - horseweed
    # colorchecker:
    #   - colorchecker
    clover:
      - crimson clover
      - red clover

  # labels used in determine_class?

concat_labels:
  data_folder: /home/jbshah/SemiF-NonTargetWeedClassifier/labels/md_covers
  output_file: /home/jbshah/SemiF-NonTargetWeedClassifier/data.csv
  batch_prefix: MD

curate:
  non_target_classes: # class to target for relabeling
    - non_target

filter: # for class_specific_labeler.py
  storage: longterm_images # GROW_DATA or longterm_images
  batch_prefix: NC
  start_date: 2022-10-12
  end_date: 2022-10-31
  sample_size: 20
  plant_classes: # include only these classes. Must be in "common names"
    # - radish
    # - mustard 
    - oats
    # - rye
    # - colorchecker
  validated: false
  season_keyword: cover
  
  class_labels:
    a: non_target
    s: grass
    d: broadleaf
    f: colorchecker
    g: flower-seed broadleaf

  # ['Black Oats', 'Cereal Rye', 'Colorchecker', 'Cultivated Radish', 'Mustards', 'Oats', 'Unknown']
  show_developed: false

  n_samples_per_category: 100
  
  area_categories:
    very_small: [0, 0.1]
    small: [0.1, 1]
    medium: [1, 10]
    medium_large: [10, 100]
    large: [100, 1000]
    very_large: [1000, 1000000]
  
  # class_labels: # for covers MD
  #   a: non_target
  #   s: clover
  #   d: winter pea
  #   f: hairy vetch
  #   g: rye
  #   h: colorchecker
  #   j: horseweed  