hydra:
  run:
    dir: ${paths.workdir}/projects/${general.project_name}/${general.sub_project_name}
  output_subdir: ${paths.workdir}/projects/${general.project_name}/${general.sub_project_name}

general:
  project_name: test
  sub_project_name: sub_test

tasks:
  - create_recipes
  # - move_cutouts
  # - synthesize